#spring related properties:
server:
  port : 8081       #the port on which the app starts
  servlet:
    context-path: /catalog    #root of all endpoints

#custom properties:

test.value: RandomString      #custom defined property